
SET SERVEROUTPUT ON;

-- DROP EXISTING TABLES 

BEGIN
    FOR I IN (
        WITH MYTABLES AS (
            SELECT 'REVIEW' AS TNAME FROM DUAL
            UNION ALL SELECT 'PAYMENT' FROM DUAL
            UNION ALL SELECT 'ORDER_ITEM' FROM DUAL
            UNION ALL SELECT 'ORDERS' FROM DUAL
            UNION ALL SELECT 'CART_ITEM' FROM DUAL
            UNION ALL SELECT 'CART' FROM DUAL
            UNION ALL SELECT 'VOUCHER' FROM DUAL
            UNION ALL SELECT 'BOOK' FROM DUAL
            UNION ALL SELECT 'AUTHOR' FROM DUAL
            UNION ALL SELECT 'PUBLISHER' FROM DUAL
            UNION ALL SELECT 'APP_USER' FROM DUAL
        )
        SELECT M.TNAME
        FROM MYTABLES M INNER JOIN USER_TABLES O ON M.TNAME = O.TABLE_NAME
    )
    LOOP
        BEGIN
            DBMS_OUTPUT.PUT_LINE('DROPPING TABLE: ' || I.TNAME);
            EXECUTE IMMEDIATE 'DROP TABLE ' || I.TNAME || ' CASCADE CONSTRAINTS';
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLERRM);
        END;
    END LOOP;
END;
/


-- STEP 2: CREATE TABLES 


-- ───────────── AUTHOR ─────────────
CREATE TABLE AUTHOR (
    AUTHOR_ID    NUMBER(6)     NOT NULL,
    AUTHOR_NAME  VARCHAR2(100) NOT NULL,
    BIO          VARCHAR2(500),
    BIRTH_DATE   DATE,
    COUNTRY      VARCHAR2(100),
    IMAGE        VARCHAR2(255),
    CONSTRAINT AUTHOR_PK PRIMARY KEY (AUTHOR_ID)
);

-- ───────────── PUBLISHER ─────────────
CREATE TABLE PUBLISHER (
    PUBLISHER_ID    NUMBER(6)     NOT NULL,
    PUBLISHER_NAME  VARCHAR2(100) NOT NULL,
    ADDRESS         VARCHAR2(255),
    PHONE           VARCHAR2(20),
    EMAIL           VARCHAR2(100),
    IMAGE           VARCHAR2(255),
    FOUNDED_DATE    DATE,
    CONSTRAINT PUBLISHER_PK PRIMARY KEY (PUBLISHER_ID),
    CONSTRAINT UK_PUBLISHER_NAME UNIQUE (PUBLISHER_NAME)
);

-- ───────────── BOOK ─────────────
CREATE TABLE BOOK (
    BOOK_ID        NUMBER(6)      NOT NULL,
    AUTHOR_ID      NUMBER(6)      NOT NULL,
    PUBLISHER_ID   NUMBER(6)      NOT NULL,
    TITLE          VARCHAR2(200)  NOT NULL,
    ISBN           VARCHAR2(20),
    PRICE          NUMBER(10,2)   NOT NULL,
    STOCK_QUANTITY NUMBER         DEFAULT 0,
    PAGE_COUNT     NUMBER,
    LANGUAGE       VARCHAR2(50)   DEFAULT 'English',
    IMAGE          VARCHAR2(255),
    STAR_RATING    NUMBER(2,1)    DEFAULT 0,
    REVIEW_COUNT   NUMBER         DEFAULT 0,
    CONSTRAINT BOOK_PK PRIMARY KEY (BOOK_ID),
    CONSTRAINT UK_BOOK_ISBN UNIQUE (ISBN),
    CONSTRAINT BOOK_AUTHOR_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID) ON DELETE CASCADE,
    CONSTRAINT BOOK_PUBLISHER_FK FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER(PUBLISHER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_BOOK_PRICE CHECK (PRICE >= 0),
    CONSTRAINT CHK_BOOK_STOCK CHECK (STOCK_QUANTITY >= 0)
);

-- ───────────── APP_USER ─────────────
CREATE TABLE APP_USER (
    USER_ID     NUMBER(6)      NOT NULL,
    NAME        VARCHAR2(100)  NOT NULL,
    EMAIL       VARCHAR2(100)  NOT NULL,
    PASSWORD    VARCHAR2(255)  NOT NULL,
    PHONE       VARCHAR2(20),
    IMAGE       VARCHAR2(255),
    ROLE        VARCHAR2(20)   DEFAULT 'customer',
    CREATED_AT  DATE           DEFAULT SYSDATE,
    CONSTRAINT APP_USER_PK PRIMARY KEY (USER_ID),
    CONSTRAINT UK_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_USER_ROLE CHECK (ROLE IN ('admin','customer'))
);

-- ───────────── CART ─────────────
CREATE TABLE CART (
    CART_ID    NUMBER(6) NOT NULL,
    USER_ID    NUMBER(6) NOT NULL,
    CREATED_AT DATE      DEFAULT SYSDATE,
    CONSTRAINT CART_PK PRIMARY KEY (CART_ID),
    CONSTRAINT CART_USER_FK FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE
);

-- ───────────── CART_ITEM ─────────────
CREATE TABLE CART_ITEM (
    CART_ITEM_ID NUMBER(10) NOT NULL,
    CART_ID      NUMBER(6)  NOT NULL,
    BOOK_ID      NUMBER(6)  NOT NULL,
    QUANTITY     NUMBER     DEFAULT 1,
    PRICE        NUMBER(10,2) NOT NULL,
    CONSTRAINT CART_ITEM_PK PRIMARY KEY (CART_ITEM_ID),
    CONSTRAINT CART_ITEM_CART_FK FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID) ON DELETE CASCADE,
    CONSTRAINT CART_ITEM_BOOK_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
    CONSTRAINT UK_CART_BOOK UNIQUE (CART_ID, BOOK_ID),
    CONSTRAINT CHK_CART_QTY CHECK (QUANTITY > 0)
);

-- ───────────── VOUCHER ─────────────
CREATE TABLE VOUCHER (
    VOUCHER_ID       NUMBER(6) NOT NULL,
    VOUCHER_CODE     VARCHAR2(50) NOT NULL,
    DISCOUNT_PERCENT NUMBER(5,2),
    VALID_FROM       DATE,
    VALID_TO         DATE,
    MINIMUM_AMOUNT   NUMBER(10,2) DEFAULT 0,
    USAGE_LIMIT      NUMBER DEFAULT 1,
    IS_ACTIVE        NUMBER(1) DEFAULT 1,
    CONSTRAINT VOUCHER_PK PRIMARY KEY (VOUCHER_ID),
    CONSTRAINT UK_VOUCHER_CODE UNIQUE (VOUCHER_CODE),
    CONSTRAINT CHK_VOUCHER_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
    CONSTRAINT CHK_VOUCHER_DISCOUNT CHECK (DISCOUNT_PERCENT BETWEEN 0 AND 100)
);

-- ───────────── ORDERS ─────────────
CREATE TABLE ORDERS (
    ORDER_ID     NUMBER(10) NOT NULL,
    USER_ID      NUMBER(6)  NOT NULL,
    VOUCHER_ID   NUMBER(6),
    ORDER_DATE   DATE       DEFAULT SYSDATE,
    TOTAL_AMOUNT NUMBER(10,2) DEFAULT 0,
    STATUS       VARCHAR2(30) DEFAULT 'Pending',
    CONSTRAINT ORDERS_PK PRIMARY KEY (ORDER_ID),
    CONSTRAINT ORDERS_USER_FK FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT ORDERS_VOUCHER_FK FOREIGN KEY (VOUCHER_ID) REFERENCES VOUCHER(VOUCHER_ID),
    CONSTRAINT CHK_ORDER_STATUS CHECK (STATUS IN ('Pending','Processing','Shipped','Delivered','Cancelled'))
);

-- ───────────── ORDER_ITEM ─────────────
CREATE TABLE ORDER_ITEM (
    ORDER_ITEM_ID NUMBER(10) NOT NULL,
    ORDER_ID      NUMBER(10) NOT NULL,
    BOOK_ID       NUMBER(6)  NOT NULL,
    QUANTITY      NUMBER     DEFAULT 1,
    PRICE         NUMBER(10,2) NOT NULL,
    CONSTRAINT ORDER_ITEM_PK PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT ORDER_ITEM_ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT ORDER_ITEM_BOOK_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID),
    CONSTRAINT CHK_ORDER_ITEM_QTY CHECK (QUANTITY > 0)
);

-- ───────────── PAYMENT ─────────────
CREATE TABLE PAYMENT (
    PAYMENT_ID     NUMBER(10) NOT NULL,
    ORDER_ID       NUMBER(10) NOT NULL,
    PAYMENT_METHOD VARCHAR2(50),
    AMOUNT         NUMBER(10,2) NOT NULL,
    PAYMENT_STATUS VARCHAR2(30) DEFAULT 'Pending',
    PAYMENT_DATE   DATE,
    TRANSACTION_ID VARCHAR2(100),
    CONSTRAINT PAYMENT_PK PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT PAYMENT_ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_PAYMENT_METHOD CHECK (PAYMENT_METHOD IN ('Credit Card','Cash on Delivery','bKash')),
    CONSTRAINT CHK_PAYMENT_STATUS CHECK (PAYMENT_STATUS IN ('Pending','Completed','Failed'))
);

-- ───────────── REVIEW ─────────────
CREATE TABLE REVIEW (
    REVIEW_ID   NUMBER(10) NOT NULL,
    USER_ID     NUMBER(6)  NOT NULL,
    BOOK_ID     NUMBER(6)  NOT NULL,
    RATING      NUMBER(2,1) NOT NULL,
    REVIEW_TEXT VARCHAR2(500),
    REVIEW_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT REVIEW_PK PRIMARY KEY (REVIEW_ID),
    CONSTRAINT REVIEW_USER_FK FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT REVIEW_BOOK_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
    CONSTRAINT UK_USER_BOOK_REVIEW UNIQUE (USER_ID, BOOK_ID),
    CONSTRAINT CHK_RATING CHECK (RATING BETWEEN 1 AND 5)
);

-- new table 
CREATE TABLE AUDIT_LOG (
    LOG_ID       NUMBER(10) NOT NULL,
    TABLE_NAME   VARCHAR2(50),
    RECORD_ID    NUMBER,
    OLD_VALUE    VARCHAR2(100),
    NEW_VALUE    VARCHAR2(100),
    CHANGED_AT   DATE DEFAULT SYSDATE,
    CONSTRAINT AUDIT_LOG_PK PRIMARY KEY (LOG_ID)
);


CREATE TABLE WISHLIST (
    WISHLIST_ID NUMBER(10) NOT NULL,
    USER_ID     NUMBER(6)  NOT NULL,
    BOOK_ID     NUMBER(6)  NOT NULL,
    ADDED_AT    DATE DEFAULT SYSDATE,
    CONSTRAINT WISHLIST_PK PRIMARY KEY (WISHLIST_ID),
    CONSTRAINT WISHLIST_USER_FK FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT WISHLIST_BOOK_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
    CONSTRAINT UK_USER_BOOK_WISHLIST UNIQUE (USER_ID, BOOK_ID)
);


