SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION CHECK_STOCK_AVAILABLE(
    P_CART_ID IN NUMBER
) RETURN NUMBER
IS
    V_OUT_OF_STOCK NUMBER := 0;
    V_BOOK_STOCK   NUMBER;
    V_REQUIRED_QTY NUMBER;
BEGIN
    FOR ITEM_REC IN (
        SELECT BOOK_ID, QUANTITY
        FROM CART_ITEM
        WHERE CART_ID = P_CART_ID
    )
    LOOP
        SELECT STOCK_QUANTITY INTO V_BOOK_STOCK
        FROM BOOK
        WHERE BOOK_ID = ITEM_REC.BOOK_ID;

        IF V_BOOK_STOCK < ITEM_REC.QUANTITY THEN
            V_OUT_OF_STOCK := 1;
            DBMS_OUTPUT.PUT_LINE('Insufficient stock for BOOK_ID: ' || ITEM_REC.BOOK_ID);
        END IF;
    END LOOP;

    RETURN V_OUT_OF_STOCK;
END;
/