
-- Trigger 1
-- Recalculate a book's star rating + review
-- count whenever a new review is inserted.


CREATE OR REPLACE TRIGGER TRG_UPDATE_BOOK_RATING
AFTER INSERT ON REVIEW
FOR EACH ROW
DECLARE
    V_OLD_AVG   NUMBER;
    V_OLD_COUNT NUMBER;
    V_NEW_AVG   NUMBER;
BEGIN
    SELECT STAR_RATING, REVIEW_COUNT
    INTO V_OLD_AVG, V_OLD_COUNT
    FROM BOOK
    WHERE BOOK_ID = :NEW.BOOK_ID;

    V_NEW_AVG := ROUND(((V_OLD_AVG * V_OLD_COUNT) + :NEW.RATING) / (V_OLD_COUNT + 1), 1);

    UPDATE BOOK
    SET STAR_RATING = V_NEW_AVG,
        REVIEW_COUNT = V_OLD_COUNT + 1
    WHERE BOOK_ID = :NEW.BOOK_ID;
END;
/