CREATE OR REPLACE TRIGGER TRG_UPDATE_BOOK_RATING
FOR INSERT ON REVIEW
COMPOUND TRIGGER

    TYPE T_BOOK_IDS IS TABLE OF REVIEW.BOOK_ID%TYPE;
    V_BOOK_IDS T_BOOK_IDS := T_BOOK_IDS();

    AFTER EACH ROW IS
    BEGIN
        V_BOOK_IDS.EXTEND;
        V_BOOK_IDS(V_BOOK_IDS.COUNT) := :NEW.BOOK_ID;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
        V_AVG_RATING NUMBER;
        V_COUNT      NUMBER;
    BEGIN
        FOR I IN 1 .. V_BOOK_IDS.COUNT LOOP
            SELECT ROUND(AVG(RATING), 1), COUNT(*)
            INTO V_AVG_RATING, V_COUNT
            FROM REVIEW
            WHERE BOOK_ID = V_BOOK_IDS(I);

            UPDATE BOOK
            SET STAR_RATING = V_AVG_RATING,
                REVIEW_COUNT = V_COUNT
            WHERE BOOK_ID = V_BOOK_IDS(I);
        END LOOP;
    END AFTER STATEMENT;

END TRG_UPDATE_BOOK_RATING;
/