SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER TRG_AUDIT_ORDER_STATUS
AFTER UPDATE OF STATUS ON ORDERS
FOR EACH ROW
DECLARE
    V_NEW_LOG_ID NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_ID), 0) + 1 INTO V_NEW_LOG_ID FROM AUDIT_LOG;

    INSERT INTO AUDIT_LOG (LOG_ID, TABLE_NAME, RECORD_ID, OLD_VALUE, NEW_VALUE, CHANGED_AT)
    VALUES (V_NEW_LOG_ID, 'ORDERS', :NEW.ORDER_ID, :OLD.STATUS, :NEW.STATUS, SYSDATE);

    DBMS_OUTPUT.PUT_LINE('Order ' || :NEW.ORDER_ID || ' status changed: ' || :OLD.STATUS || ' -> ' || :NEW.STATUS);
END;
/